version: '2'
services:
  node1:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code

  node2:
    build: .
    command: python blockchain.py 5001
    ports:
     - "5001:5001"
    volumes:
     - .:/code
